@Magaza.Api_HostAddress = http://localhost:5201

### Etiket oluştur
POST {{host}}/api/labels
Content-Type: application/json

{"name": "Pantolon"}

### Satış oluştur
POST {{host}}/api/sales
Content-Type: application/json

{
    "label": "Pantolon",
    "unitPrice": 700,
    "quantity": 1,
    "paymentMethod": "nakit"
}

### Satışları Listele
GET {{host}}/api/sales

### Satış Sil
DELETE {{host}}/api/sales/1

### Bozuk istek - 400 görmelisin
POST {{host}}/api/sales
Content-Type: application/json

{"label": "Tişört", "unitPrice": -5, "quantity". 1, "paymentMethod": "nakit"}